name: Build Test Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the Repository
      uses: actions/checkout@v4
    - name: Use Node.js 20
      uses: actions/setup-node@v4
      with:
        node-version: 20.x
        cache: 'npm'
    - name: Install Dependencies
      run: npm ci
    - name: Update the config
      run: echo "export const settings = {host:\"http://localhost:3030\"};" > src/config.js
    - name: Start Backend Server
      run: npm run start:be &
    - name: Start Frontend
      run: npm run start:fe &
    - name: Install PLaywright Browsers
      run: npx playwright install     
    - name: Run Tests
      run: npm run test:ui

  deploy_be:
    runs-on: ubuntu-latest
    needs: build_test
    steps:
        - uses: actions/checkout@v3
        - uses: JorgeLNJunior/render-deploy@v1.4.4
          with:
            service_id: ${{ secrets.RENDER_SERVICE_BE_ID }}
            api_key: ${{ secrets.RENDER_API_KEY }}
            wait_deploy: true 

  deploy_fe:
    runs-on: ubuntu-latest
    needs: deploy_be
    steps:
        - uses: actions/checkout@v3
        - uses: JorgeLNJunior/render-deploy@v1.4.4
          with:
            service_id: ${{ secrets.RENDER_SERVICE_FE_ID }}
            api_key: ${{ secrets.RENDER_API_KEY }}
            wait_deploy: true 
